### ISSUE TITLE
Payday command & kill player

### ISSUE THREAD

**Issue by ustaalon** [LethalCompany/LethalAPI.TerminalCommands#30]
Maybe because its a library, we can remove those commands to be in a separated mod/mod pack?

+ When entering "payday" and then the amount, this error occurred: 
![image](https://github.com/LethalCompany/LethalAPI.Terminal/assets/19238320/095d4a55-69ea-43a2-8f2e-01edf7a2cbd4)

**Comment by ShimmyMySherbet** [comment]
I see what happened. I wrote the example commands for the updated ReadMe inside of Visual Studio for the intelisense, but must have built the project again and collected the dll later.
Those commands were never meant to be included in any release. I have since updated the mod on Thunderstore to remove those commands.

Additionally, the error there is being caused by an error on my part. You're not supposed to register the `Terminal` instance using `WithContext()`, as the terminal instance is always pre-registered to interactions. So I'll also have to update the ReadMe.
